# Doctrine Configuration
doctrine:
  dbal:
    types:
      enumtransactiontype: Beldougie\CommonBundle\DBAL\Types\EnumTransactionType
    connections:
      default:
        mapping_types: 
          enum: string 
  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        mappings:
          BeldougieCommonBundle: ~

